- name: Setup Landing Page
  hosts: loadbalancer
  become: yes
  vars:
    domain: 34.41.141.71
    server:
      - host: 34.136.213.252
        name: landingpage-01
      - host: 34.28.16.13
        name: landingpage-02
  roles: 
    - update-os
    - load-balancer

#ansible-playbook -i inventory setup-load-balancer.yml